require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  Version: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/**/*"

# Reglas específicas que puedes ajustar
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 120

Layout/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
